[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/hashicorp/go-plugin"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1"

[[constraint]]
  name = "github.com/mitchellh/go-ps"
  branch = "master"

[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  version = "1"

[[constraint]]
  name = "github.com/pinpt/go-common"
  version = "6"

[[constraint]]  
  name = "github.com/kardianos/service"
  branch = "master"