[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/hashicorp/go-plugin"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1"

[[constraint]]
  name = "github.com/mitchellh/go-ps"
  branch = "master"

#[[constraint]]
#  name = "github.com/fsnotify/fsnotify"
#  version = "1"

[[constraint]]
  name = "github.com/pinpt/go-common"
  version = "8"

[[constraint]]  
  name = "github.com/kardianos/service"
  branch = "master"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  version = "1"

[[constraint]]
  name = "github.com/pinpt/integration-sdk"
  version = "0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2"

[[constraint]]
  name = "github.com/denisbrodbeck/machineid"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/99designs/keyring"
  
[[constraint]]
  name = "github.com/pinpt/ripsrc"
  version = "6"

# dependency of ripsrc

[[override]]
  name = "gopkg.in/src-d/go-license-detector.v2"
  version = "=2.0.0"

# dependencies of ripsrc, go-license-detector

[[override]]
  name = "gopkg.in/src-d/go-git.v4"
  version = "=4.7.0"